version: '3.7'
services:
  proxy:
    image: nginx
    container_name: collectionbrowse-admin
    networks:
      - loopback
    ports:
      - 8080:8080
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - loopback

networks:
  loopback:
